name = "slash-tags"
type = "webpack"
account_id = ""
workers_dev = true

[env.development]
vars= { APPLICATION_ID = "" }
kv_namespaces = [{ binding = "GUILD_TAGS", preview_id = "" }]

[env.production]
vars= { APPLICATION_ID = "" }
kv_namespaces = [{ binding = "GUILD_TAGS", id = "" }]
