name = "slash-tags"
main = "index.js"
compatibility_date = "2025-06-17"
compatibility_flags = ["nodejs_compat"]

[vars]
APPLICATION_ID = ""
BOT_TOKEN = ""
PUBLIC_KEY = ""

[env.development]
vars = { APPLICATION_ID = "", BOT_TOKEN = "", PUBLIC_KEY = "" }
kv_namespaces = [
  { binding = "GUILD_TAGS", id = "preview", preview_id = "" }
]

[env.production]
vars = { APPLICATION_ID = "", BOT_TOKEN = "", PUBLIC_KEY = "" }
kv_namespaces = [
  { binding = "GUILD_TAGS", id = "" }
]
