//  @formatter:off
module.exports = {
  createInstantInvite:     BigInt(1) << BigInt(0),
  kickMembers:             BigInt(1) << BigInt(1),
  banMembers:              BigInt(1) << BigInt(2),
  administrator:           BigInt(1) << BigInt(3),
  manageChannels:          BigInt(1) << BigInt(4),
  manageGuild:             BigInt(1) << BigInt(5),
  addReactions:            BigInt(1) << BigInt(6),
  viewAuditLog:            BigInt(1) << BigInt(7),
  prioritySpeaker:         BigInt(1) << BigInt(8),
  stream:                  BigInt(1) << BigInt(9),
  viewChannel:             BigInt(1) << BigInt(10),
  sendMessages:            BigInt(1) << BigInt(11),
  sendTTSMessages:         BigInt(1) << BigInt(12),
  manageMessages:          BigInt(1) << BigInt(13),
  embedLinks:              BigInt(1) << BigInt(14),
  attachFiles:             BigInt(1) << BigInt(15),
  readMessageHistory:      BigInt(1) << BigInt(16),
  mentionEveryone:         BigInt(1) << BigInt(17),
  useExternalEmojis:       BigInt(1) << BigInt(18),
  viewGuildInsights:       BigInt(1) << BigInt(19),
  connect:                 BigInt(1) << BigInt(20),
  speak:                   BigInt(1) << BigInt(21),
  muteMembers:             BigInt(1) << BigInt(22),
  deafenMembers:           BigInt(1) << BigInt(23),
  moveMembers:             BigInt(1) << BigInt(24),
  useVAD:                  BigInt(1) << BigInt(25),
  changeNickname:          BigInt(1) << BigInt(26),
  manageNicknames:         BigInt(1) << BigInt(27),
  manageRoles:             BigInt(1) << BigInt(28),
  manageWebhooks:          BigInt(1) << BigInt(29),
  manageEmojis:            BigInt(1) << BigInt(30),
  useSlashCommands:        BigInt(1) << BigInt(31),
};
